-- ======================================================
-- ESMAELX ELITE STORE V11 - ESTRUTURA FINAL (CORRIGIDA)
-- ======================================================

-- 1. TABELA DE APLICATIVOS (ID BIGINT evita erro de sintaxe UUID)
CREATE TABLE IF NOT EXISTS public.apps (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title text NOT NULL,
    "packageName" text NOT NULL,
    version text,
    size text,
    category text DEFAULT 'All',
    rating float4 DEFAULT 5.0,
    downloads text DEFAULT '0',
    icon text,
    banner text,
    description text,
    "modFeatures" text[] DEFAULT '{}',
    "isPremium" boolean DEFAULT false,
    "isVerified" boolean DEFAULT true,
    author text DEFAULT 'EsmaelX Mods',
    "downloadUrl" text DEFAULT '#',
    "lastUpdate" text DEFAULT 'Recente',
    created_at timestamptz DEFAULT now()
);

-- 2. TABELA DE MEMBROS (Suporta IDs numéricos longos sem erro)
CREATE TABLE IF NOT EXISTS public.members (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username text UNIQUE NOT NULL,
    access_code text NOT NULL,
    full_name text,
    is_premium boolean DEFAULT true,
    expiry_date timestamptz NOT NULL,
    created_at timestamptz DEFAULT now()
);

-- 3. TABELA DE CONFIGURAÇÕES
CREATE TABLE IF NOT EXISTS public.system_settings (
    id int PRIMARY KEY DEFAULT 1,
    maintenance_enabled boolean DEFAULT false,
    maintenance_message text DEFAULT 'O sistema está em manutenção.',
    CONSTRAINT single_row CHECK (id = 1)
);

-- 4. SEGURANÇA (Habilitar RLS)
ALTER TABLE public.apps ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.members ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.system_settings ENABLE ROW LEVEL SECURITY;

-- Criar Políticas de Leitura Pública
DROP POLICY IF EXISTS "Permitir leitura pública de apps" ON public.apps;
CREATE POLICY "Permitir leitura pública de apps" ON public.apps FOR SELECT USING (true);

DROP POLICY IF EXISTS "Permitir leitura pública de membros" ON public.members;
CREATE POLICY "Permitir leitura pública de membros" ON public.members FOR SELECT USING (true);

DROP POLICY IF EXISTS "Permitir leitura pública de configurações" ON public.system_settings;
CREATE POLICY "Permitir leitura pública de configurações" ON public.system_settings FOR SELECT USING (true);

-- 5. CONFIGURAÇÃO INICIAL DO SISTEMA
INSERT INTO public.system_settings (id, maintenance_enabled, maintenance_message) 
VALUES (1, false, 'EsmaelX Elite Online') ON CONFLICT (id) DO NOTHING;

-- ======================================================
-- COMANDO PARA CRIAR USUÁRIO COM 3 DIAS DE VALIDADE:
-- ======================================================
INSERT INTO public.members (username, access_code, full_name, is_premium, expiry_date)
VALUES (
    'esmael_vip', 
    'VIP-3-DIAS', 
    'Assinante Vip Temporário', 
    true, 
    NOW() + INTERVAL '3 days'
) ON CONFLICT (username) DO NOTHING;