
-- ======================================================
-- ESMAELX ELITE STORE V11 - ESTRUTURA COMPLETA (REVISADA)
-- ======================================================

-- 1. LIMPEZA (OPCIONAL - use se quiser resetar as tabelas)
-- DROP TABLE IF EXISTS public.apps;
-- DROP TABLE IF EXISTS public.members;
-- DROP TABLE IF EXISTS public.system_settings;

-- 2. TABELA DE APLICATIVOS (APPS)
CREATE TABLE IF NOT EXISTS public.apps (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title text NOT NULL,
    "packageName" text NOT NULL,
    version text DEFAULT '1.0.0',
    size text DEFAULT '0 MB',
    category text DEFAULT 'Apps', -- Categorias: 'Apps', 'Games', 'Premium'
    rating float4 DEFAULT 5.0,
    downloads text DEFAULT '0',
    icon text,
    banner text,
    description text,
    "modFeatures" text[] DEFAULT '{}',
    "isPremium" boolean DEFAULT false,
    "isVerified" boolean DEFAULT true,
    author text DEFAULT 'Esmael Mods',
    "downloadUrl" text DEFAULT '#',
    "lastUpdate" text DEFAULT 'Recente',
    created_at timestamptz DEFAULT now()
);

-- 3. TABELA DE MEMBROS (USUÁRIOS ELITE)
CREATE TABLE IF NOT EXISTS public.members (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username text UNIQUE NOT NULL,
    access_code text NOT NULL,
    full_name text,
    is_premium boolean DEFAULT true,
    expiry_date timestamptz NOT NULL,
    created_at timestamptz DEFAULT now()
);

-- 4. TABELA DE CONFIGURAÇÕES (MANUTENÇÃO)
CREATE TABLE IF NOT EXISTS public.system_settings (
    id int PRIMARY KEY DEFAULT 1,
    maintenance_enabled boolean DEFAULT false,
    maintenance_message text DEFAULT 'O sistema está em manutenção para melhorias.',
    CONSTRAINT single_row CHECK (id = 1)
);

-- 5. SEGURANÇA (Habilitar Row Level Security)
ALTER TABLE public.apps ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.members ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.system_settings ENABLE ROW LEVEL SECURITY;

-- Criar Políticas de Leitura (Permite que o site leia os dados sem login administrativo)
DROP POLICY IF EXISTS "Permitir leitura pública de apps" ON public.apps;
CREATE POLICY "Permitir leitura pública de apps" ON public.apps FOR SELECT USING (true);

DROP POLICY IF EXISTS "Permitir leitura pública de membros" ON public.members;
CREATE POLICY "Permitir leitura pública de membros" ON public.members FOR SELECT USING (true);

DROP POLICY IF EXISTS "Permitir leitura pública de configurações" ON public.system_settings;
CREATE POLICY "Permitir leitura pública de configurações" ON public.system_settings FOR SELECT USING (true);

-- 6. DADOS DE EXEMPLO (OPCIONAL - Para testar o site imediatamente)

-- Configuração inicial do Sistema
INSERT INTO public.system_settings (id, maintenance_enabled, maintenance_message) 
VALUES (1, false, 'EsmaelX Elite Store Online') 
ON CONFLICT (id) DO UPDATE SET maintenance_enabled = EXCLUDED.maintenance_enabled;

-- Usuário de Teste (Válido por 30 dias)
INSERT INTO public.members (username, access_code, full_name, is_premium, expiry_date)
VALUES (
    'esmael_admin', 
    'ELITE-2025', 
    'Esmael Desenvolvedor', 
    true, 
    NOW() + INTERVAL '30 days'
) ON CONFLICT (username) DO NOTHING;

-- Exemplos de Apps e Jogos
INSERT INTO public.apps (title, "packageName", version, size, category, rating, downloads, icon, banner, description, "modFeatures", "isPremium", "isVerified", author, "downloadUrl")
VALUES 
(
    'WhatsApp Aero', 
    'com.aero.whatsapp', 
    '10.12', 
    '65 MB', 
    'Apps', 
    5.0, 
    '1.2M', 
    'https://play-lh.googleusercontent.com/bY7R2ZzjyS9yLp1iJp8Qz8-y6Y1y-z8Y1y-z8Y1y-z8Y', 
    'https://picsum.photos/seed/waero/1200/600', 
    'Versão modificada do WhatsApp com temas e privacidade extrema.', 
    '{"Anti-Ban", "Temas Custom", "Privacidade Full"}', 
    false, 
    true, 
    'Esmael Mods', 
    '#'
),
(
    'GTA San Andreas Mod', 
    'com.rockstargames.gtasa', 
    '2.10', 
    '1.8 GB', 
    'Games', 
    4.9, 
    '500K', 
    'https://play-lh.googleusercontent.com/9-3y8Y1y-z8Y1y-z8Y1y-z8Y1y-z8Y1y-z8Y1y-z8Y', 
    'https://picsum.photos/seed/gta/1200/600', 
    'O clássico GTA com menu de cheats e gráficos remasterizados.', 
    '{"Menu Cleo", "Dinheiro Infinito", "Gráficos HD"}', 
    true, 
    true, 
    'Esmael Mods', 
    '#'
);
