
export interface MovieItem {
  id: string;
  title: string;
  category: 'Ação' | 'Terror' | 'Comédia' | 'Ficção' | 'Drama' | 'Série';
  rating: number;
  year: string;
  duration: string;
  poster: string;
  backdrop: string;
  description: string;
  actors: string[]; // Alterado de cast para actors
  isPremium: boolean;
  isVerified: boolean;
  director: string;
  videoUrl: string;
  downloadUrl: string;
}

export type Category = 'All' | 'Ação' | 'Terror' | 'Comédia' | 'Ficção' | 'Drama' | 'Série';
export type Language = 'pt' | 'en' | 'es' | 'ru' | 'fr' | 'it' | 'ko' | 'ja';
export type ThemeColor = 'blue' | 'emerald' | 'rose' | 'amber' | 'purple' | 'cyan' | 'red' | 'orange' | 'lime' | 'fuchsia';
export type SortOption = 'default' | 'rating' | 'name' | 'year';

export interface TranslationSchema {
  heroTitle: string;
  heroDesc: string;
  searchPlaceholder: string;
  devLabel: string;
  systemOnline: string;
  latency: string;
  uptime: string;
  tickerMsgs: string[];
  categoryAll: string;
  categoryAction: string;
  categoryHorror: string;
  categoryComedy: string;
  categorySciFi: string;
  categoryDrama: string;
  categorySeries: string;
  noResults: string;
  sortBy: string;
  sortName: string;
  sortRating: string;
  sortYear: string;
  recent: string;
  favorites: string;
  tryAgain: string;
  verifiedOfficial: string;
  qualityCertified: string;
  systemLibrary: string;
  exploringDatabase: string;
  waitingProjects: string;
  supabaseError: string;
  aboutMovie: string;
  downloadBtn: string;
  watchBtn: string;
  generatingLink: string;
  redirecting: string;
  movieEdition: string;
  directorLabel: string;
  yearLabel: string;
  durationLabel: string;
  ratingLabel: string;
  optimizedText: string;
  verifiedBy: string;
  secureProtocol: string;
  scanSteps: string[];
  reverseEngineering: string;
  devSpecialist: string;
  age: string;
  level: string;
  devDesc: string;
  aboutSystem: string;
  connect: string;
  message: string;
  telegram: string;
  aiChatTitle: string;
  aiChatPlaceholder: string;
  aiWelcome: string;
  aiMaintenance: string;
  aiError: string;
  aiLoading: string;
  aiAnalysis: string;
  experimentalTip: string;
  mainFeatures: string;
  amoledOptimization: string;
  auroraOn: string;
  amoledOn: string;
  visualAtmosphere: string;
  languageSelect: string;
}
